version: '3'
services:
  nginx-server:
    image: nginx
    volumes:
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-network

  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    networks:
      - nginx-network

networks:
  nginx-network:
