# This workflow will install Python dependencies and run tests 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quality Assurance (Certificates)
on:
  pull_request: 
    types: [ opened, synchronize, reopened, edited, review_request_removed ] 
jobs:
  certificate-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: contains(github.head_ref, 'onboardingRequest')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run QA checks
      env:
        REPORT_OUTPUT: folder_test_md_report.md
      shell: bash
      run: |
        echo "REPORT_FILE=${REPORT_OUTPUT}" >> "$GITHUB_ENV"
        pytest -vs scripts/tests/test_country_folders.py --country-mode -C ${{  github.head_ref }} --tb=short -rfEx --md-report --md-report-verbose=1 --md-report-zeros=number --md-report-flavor gfm --md-report-exclude-outcomes xpassed xfailed --md-report-output "$REPORT_OUTPUT" --html=tng_onboarding_qa.html --self-contained-html --junit-xml=pytest.xml
    - name: Publish Test Results
      id: test-results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          pytest.xml

    - name: List generated test files
      if: always()
      run: ls -l

    - name: Print content of tng_onboarding_qa.html
      if: always()
      run: cat tng_onboarding_qa.html

    - name: Print content of pytest.xml
      if: always()
      run: cat pytest.xml

    - name: Print content of folder_test_md_report.md
      if: always()
      run: cat folder_test_md_report.md

    - name: Render the report to the PR
      uses: marocchino/sticky-pull-request-comment@v2
      if: always()
      with:
        header: folder-test-report
        recreate: true
        path: ${{ env.REPORT_FILE }}


