name: QA Check
on:
  pull_request:
   branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'onboardingRequest')
    steps:
    - uses: actions/checkout@v2
    - name: Run QA Check
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 
        echo Run here Script (branch is head_ref) $GITHUB_HEAD_REF
    
