name: QA Check
on:
  pull_request:
   branches: ['main']
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      run: echo running on branch ${GITHUB_REF##*/}
