# This is a basic workflow to help you get started with Actions

name: Resign Country Onbboarding

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      countrycode:
        required: false
        type: string
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/checkout@v3
      - name: Configure Bot
        run: |
          git config --global user.email ${{secrets.BOT_EMAIL_GITHUB}}
          git config --global user.name ${{secrets.BOT_USER_GITHUB}}
          git config --global user.password ${{secrets.BOT_TOKEN_GITHUB}}
          git config --global pull.rebase true
          git config --global branch.autosetuprebase always
      - name: Resign
        env:
           BOT_TOKEN_GITHUB: ${{secrets.BOT_TOKEN_GITHUB}}
           GITHUB_TOKEN: ${{secrets.BOT_TOKEN_GITHUB}}
        run: | 
            #!/bin/bash
            SEARCH_STRING= ${{github.event.inputs.countrycode}}
            
            found=false
            
            for dir in [A-Z]*; do
              if [ -d "$dir" ] && [[ "$dir" == *"$SEARCH_STRING"* ]]; then
                found=true
                   if [ -d "$dir/signed" ]; then
                      find "$dir" -type d -name "signed" -exec rm -rf {} +
                      git checkout -b "$dir"
                      git add .
                      git commit -m "PR created from Bot for resigning $dir"
                      git push -u origin "$dir"
                      gh pr create -B main -H $dir --title 'Bot requested a change for '$dir'.' --body 'Please merge the onnboarding request of '$dir'.' > /dev/null 2>&1
                   fi
                break
              fi
            done
            
            if [ "$found" = false ]; then
              for dir in [A-Z]*; do
                if [ -d "$dir" ]; then
                   if [ -d "$dir/signed" ]; then
                      echo "A new branch for all" 
                      #find "$dir" -type d -name "signed" -exec rm -rf {} +
                      #git checkout -b "$dir"
                      #git add .
                      #git commit -m "PR created from Bot for resigning $dir"
                      #git push -u origin "$dir"
                      #gh pr create -B main -H $dir/resign --title 'Bot requested a change for '$dir'.' --body 'Please merge the onnboarding request of '$dir'.' > /dev/null 2>&1
                   fi         
                fi
              done
            fi
