name: New Check Country Delivery

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Export Secrets to File
        run: |
          echo '${{ toJSON(secrets) }}' > secrets.json

      - name: Filter Secrets for Countries
        run: |
          jq 'with_entries(select(.key | length == 3))' secrets.json > countries_raw.json

      - name: Debug Filtered Secrets
        run: |
          echo "Filtered Secrets:"
          cat countries_raw.json

      - name: Upload Filtered Secrets
        uses: actions/upload-artifact@v4
        with:
          name: countries_raw.json
          path: countries_raw.json
          overwrite: true

  delivery:
    runs-on: ubuntu-latest
    environment: dev
    needs: [prepare]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/checkout@v3
      - name: Configure Python
        run: |
          pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Configure Bot
        run: |
          git config --global user.email ${{secrets.BOT_EMAIL_GITHUB}}
          git config --global user.name ${{secrets.BOT_USER_GITHUB}}
          git config --global user.password ${{secrets.BOT_TOKEN_GITHUB}}
          git config --global pull.rebase true
          git config --global branch.autosetuprebase always

      - name: Download countries.json
        uses: actions/download-artifact@v4
        with:
          name: countries_raw.json
          path: scripts

      - name: Debug Artifact
        run: |
          echo "Files in the scripts directory:"
          ls -la scripts

      - name: Onboarding
        id: Onboarding
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN_GITHUB}}
          BOT_TOKEN_GITHUB: ${{secrets.BOT_TOKEN_GITHUB}}
          GITHUB_JOB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TRANSITIVE_TRUST_SOURCE: ${{vars.TRANSITIVE_TRUST_SOURCE}}
          NB_UP_SIGNING_PUB: ${{secrets.NB_UP_SIGNING_PUB}}
          NB_UP_SIGNING_KEY: ${{secrets.NB_UP_SIGNING_KEY}}
          ENV: ${{vars.ENV}}
          SIGN_TA_KEY: ${{secrets.TNG_TA_PRIVATE_KEY}}
          SIGN_TA_PEM: ${{secrets.TNG_TA_CA}}
          ALLOWED_DOMAINS: ${{vars.ALLOWED_DOMAINS}}
        run: |
          python scripts/delivery_new.py
